version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: shourty-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: shourty_user
      POSTGRES_PASSWORD: shourty_pass
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shourty_user -d shortener"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
